name: Testes com PHPUnit

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  phpunit:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v3

      - name: Instalar PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Instalar dependências com Composer
        run: composer install

      - name: Executar testes com PHPUnit
        run: vendor/bin/phpunit tests
